//! Curated external declarations for well-known public gem namespaces
//! (bead ita-3gs, extended by bead ita-dpg.1). See `declarations/gems.rbi`
//! (embedded below) for the entry rule and the full rationale;
//! `declarations/rbs_collection.rbi` (bead ita-dpg.1) is its
//! machine-generated sibling — see `scripts/gen-rbs-collection-pack.rb`'s
//! own header for ITS entry rule (a frozen 21-gem `gem_rbs_collection`
//! walk, regenerated by that script, never hand-edited). This module is
//! deliberately thin — just the two `include_str!`s and a call into
//! `index.rs`'s existing prism walk (`parse_defs_text`, the same one
//! `file_defs` uses for real project files), so there is exactly one way
//! this crate ever turns Ruby text into `ClassFragment`s.

use crate::index::{parse_defs_text, ClassFragment};

/// Embedded at compile time — no path discovered at runtime, no config,
/// works on any machine. Loading a project's own real `.rbi`/`.rbs` from
/// e.g. its `sorbet/` directory is a separate, later capability (bead
/// ita-vto); this is itaruby's own curated set, versioned in this repo.
pub(crate) const GEMS_RBI: &str = include_str!("../declarations/gems.rbi");

/// Generated rbs-collection pack (bead ita-dpg.1) — see
/// `scripts/gen-rbs-collection-pack.rb` and this file's own embedded
/// header for provenance. Same embedding shape as `GEMS_RBI` (no runtime
/// path, versioned in this repo); kept as a separate constant/file rather
/// than merged text so its own generation command stays self-contained
/// and regenerating it never touches the hand-curated file.
pub(crate) const RBS_COLLECTION_RBI: &str = include_str!("../declarations/rbs_collection.rbi");

/// Every fragment either declarations file declares, in that order
/// (`GEMS_RBI` first). Reparsed on every call rather than cached: both
/// files are small, and `project_index` (the only caller) is itself
/// salsa-memoized against real project file edits — not worth a cache for
/// text that never changes at runtime.
pub fn declared_fragments() -> Vec<ClassFragment> {
    let mut fragments = parse_defs_text(GEMS_RBI).fragments;
    fragments.extend(parse_defs_text(RBS_COLLECTION_RBI).fragments);
    fragments
}

/// Only `RBS_COLLECTION_RBI`'s own fragments (bead ita-dpg.1) — split out
/// from `declared_fragments()`'s merged view so the generated pack's own
/// contract (no methods, no value constants, checked over the WHOLE
/// file — see `tests/declarations.rs`) can be verified in isolation from
/// the hand-curated `gems.rbi`, which already has its own equivalent
/// check below (`declares_open_namespaces_only_no_methods`).
pub fn rbs_collection_fragments() -> Vec<ClassFragment> {
    parse_defs_text(RBS_COLLECTION_RBI).fragments
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Structural guard on the "resolves the constant and nothing else"
    /// contract (bead ita-3gs's design invariant): this file must never
    /// carry a method definition, because `open = true` is meant to come
    /// entirely from `index.rs::merge_declared_fragment`'s unconditional
    /// force, never from something declared here (e.g. an accidental
    /// `method_missing` shim, or a real method that would let a checker
    /// claim knowledge of the gem's actual behavior).
    #[test]
    fn declares_open_namespaces_only_no_methods() {
        let frags = declared_fragments();
        assert!(!frags.is_empty(), "expected at least one declared fragment");
        for f in &frags {
            assert!(f.methods.is_empty(), "{} must declare zero methods", f.path);
            assert!(
                f.singleton_methods.is_empty(),
                "{} must declare zero singleton methods",
                f.path
            );
        }
    }

    /// Every name from the 2026-08-20 measurement this bead is allowed to
    /// declare must actually resolve after parsing — a typo here would
    /// silently regress the whole point of the file.
    #[test]
    fn declares_every_measured_gem_name() {
        let frags = declared_fragments();
        let paths: Vec<&str> = frags.iter().map(|f| f.path.as_str()).collect();
        for expected in [
            "T",
            "T::Array",
            "T::Hash",
            "T::Boolean",
            "T::Sig",
            "T::Struct",
            "Rails",
            "ActiveRecord::Base",
            "ActiveRecord::RecordNotFound",
            "ActiveSupport::Concern",
            "ActiveStorage::Blob",
            "Sidekiq::Worker",
            "Dry::Initializer",
            "I18n",
            "Money",
            "Flipper",
            "Appsignal",
            "Sentry",
            "Turbo::StreamsChannel",
            "Mail::Message",
            "Mail::Address",
            "TracePoint",
        ] {
            assert!(paths.contains(&expected), "missing declared name: {expected}");
        }
        // ID/Boolean/Int (bare) are app-local aliases, not gem API — must
        // never be declared, see this module's doc comment / the .rbi
        // header.
        for excluded in ["ID", "Boolean", "Int"] {
            assert!(
                !paths.contains(&excluded),
                "{excluded} is an app-local alias, not gem API — must not be declared"
            );
        }
    }

    /// Bead ita-dpg.3 (2026-08-26): a second, test-framework-heavy batch
    /// measured across 5 public repos (rails, discourse, chatwoot,
    /// zammad, ruby-lsp). Split from `declares_every_measured_gem_name`
    /// so a mutant that deletes exactly one of these entries fails only
    /// this test, never the unrelated 2026-08-20 batch above.
    #[test]
    fn declares_the_ita_dpg_3_measured_batch() {
        let frags = declared_fragments();
        let paths: Vec<&str> = frags.iter().map(|f| f.path.as_str()).collect();
        for expected in [
            "Fabricate",
            "RSpec",
            "RSpec::Matchers",
            "FactoryBot",
            "MultiJson",
            "Test::Unit::TestCase",
            "Minitest::Assertion",
            "JWT",
            "ROTP::TOTP",
            "Audited::Audit",
            "Logster",
            "RubyLLM",
            "OmniAuth::AuthHash",
            "Addressable::URI",
            "Loofah",
            "Koala::Facebook::API",
        ] {
            assert!(paths.contains(&expected), "missing declared name: {expected}");
        }
    }

    /// The generated pack must never declare a namespace this checker
    /// already models itself. A gem's `.rbs` reopens core classes to
    /// declare its extensions (activesupport's reopens `String`,
    /// `Object`, `Kernel`, `Time`, ...), and `merge_declared_fragment`
    /// force-opens every path it merges — so one such entry silently
    /// turns off conclusive E0101 for that core receiver in EVERY
    /// project. Measured: the first generation of this file carried 40
    /// such entries and `agent_format.rs` stopped seeing `undefined
    /// method 'push' for 'String'`. The generator excludes them by top
    /// segment (`core_stdlib_tops`); this is the check that fails if a
    /// regeneration ever loses that filter.
    #[test]
    fn pack_never_reopens_a_core_class() {
        for f in rbs_collection_fragments() {
            let top = f.path.split("::").next().unwrap_or(&f.path);
            assert!(
                !crate::core::is_known_core_constant(top),
                "{} reopens core `{top}` — force-opening it kills conclusive E0101 on that receiver",
                f.path
            );
        }
    }

    /// Bead ita-dpg.2: the generator's value-constant arm
    /// (`scripts/gen-rbs-collection-pack.rb`'s `VALUE_CONST_RE`) must
    /// actually reach the residual E0104 family it was built for —
    /// measured, real gem `.rbs` value constants declared under an
    /// already-namespaced owner, both the bare-nested shape
    /// (`Rack::CONTENT_TYPE`/`Rack::SET_COOKIE` inside `module Rack`,
    /// `Rack::Utils::HTTP_STATUS_CODES` inside the nested `module Utils`)
    /// and the compact-qualified shape (`Nokogiri::XML::Node::
    /// ENTITY_REF_NODE`/`Nokogiri::XML::ParseOptions::NOBLANKS`, written
    /// at nokogiri's `.rbs` top level with no enclosing block). A
    /// regeneration that silently drops the value-constant arm (or
    /// narrows it back to namespace-only) fails this without touching
    /// `declares_every_measured_gem_name` at all — that test only checks
    /// namespace paths.
    #[test]
    fn declares_every_measured_value_constant() {
        let frags = rbs_collection_fragments();
        let paths: Vec<&str> = frags.iter().map(|f| f.path.as_str()).collect();
        for expected in [
            "Rack::CONTENT_TYPE",
            "Rack::SET_COOKIE",
            "Rack::Utils::HTTP_STATUS_CODES",
            "Nokogiri::XML::Node::ENTITY_REF_NODE",
            "Nokogiri::XML::ParseOptions::NOBLANKS",
        ] {
            assert!(paths.contains(&expected), "missing harvested value constant: {expected}");
        }
    }
}
